---
meats:
  name: string
  cut: string
  safe_temp: integer

meals:
  name: string
  sides: text
  recipe_id: id
  made_on: date

cooking_methods:
  name: string
  duration: integer
  temperature: integer
  description: text

meal_recipes:
  name: string
  meat_id: string
  method_id: string
  directions: text
  ingredients: text