---
meats: &meat
  name: string
  cut: string
  safe_temp: integer

meals: &meals
  name: string
  meat_id: id
  method_id: id
  sides: text

methods: &methods
  name: string
  duration: integer
  temperature: integer

recipes: &recipes
  name: string
  meat_id: string
  method_id: string
  directions: text
  ingredients: text